'use client';
import toast from 'react-hot-toast';
import { useEffect, useRef, useState } from 'react';
import { LuPlus, LuRefreshCw, LuPencil, LuTrash2, LuPower, LuX } from 'react-icons/lu';
import { IconPicker, IconPreview, type IconChoice } from '@/components/icons/icon-picker';
type Benefit = { id:string; title:string; description:string; icon:IconChoice|null; position:number; active:boolean };
type Document = {items:Benefit[];version:number};
export function BenefitsManager({ endpoint = '/api/v1/auth/benefits', title = 'Trust Highlights', description = 'Manage the shopping benefits displayed below the homepage hero slider.', visibilityLabel = 'Show on the homepage' }: { endpoint?: string; title?: string; description?: string; visibilityLabel?: string }) {
 const [data,setData]=useState<Document|null>(null); const [draft,setDraft]=useState<Benefit|null>(null); const [picker,setPicker]=useState(false);
 const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [reload,setReload]=useState(0); const [conflict,setConflict]=useState(false);const saving=useRef(false);
 useEffect(() => {const controller=new AbortController();fetch(endpoint,{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok) throw new Error(j.error?.message||'Could not load benefits.');setData(j.data);setError('');setConflict(false)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[reload,endpoint]);
 async function save(items:Benefit[], message = 'Benefits updated successfully.') {if(!data||saving.current||conflict)return false;saving.current=true;setBusy(true);setError('');try{const r=await fetch(endpoint,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,version:data.version}),signal:AbortSignal.timeout(15000)});const j=await r.json();if(r.status===409)setConflict(true);if(!r.ok)throw new Error(j.error?.message||'Could not save benefits.');setData(j.data);toast.success(message);return true}catch(e){const message = e instanceof Error ? e.message : 'Could not save.';setError(message);toast.error(message);return false}finally{saving.current=false;setBusy(false)}}
 const disabled=busy||loading||conflict;
 return <section className="benefits-management"><div className="benefits-heading"><div><small>STORE SETTINGS</small><h1>{title}</h1><p>{description}</p></div><div className="benefits-actions"><button aria-label="Refresh benefits" disabled={busy||loading} onClick={()=>{if(draft&&!window.confirm('Discard current edit and reload?'))return;setDraft(null);setLoading(true);setReload(reload+1)}}><LuRefreshCw /></button><button className="benefits-primary" disabled={disabled||!data||!!draft||data.items.length>=50} onClick={()=>setDraft({id:crypto.randomUUID(),title:'',description:'',icon:null,position:Math.min(100000,Math.max(-1,...(data?.items.map(i=>i.position)??[]))+1),active:true})}><LuPlus />Add Content</button></div></div>
 {error&&<p role="alert" className="benefits-error">{error} Use Refresh to reload.</p>}
 {draft&&<form className="benefits-editor" onSubmit={async e=>{e.preventDefault();if(!data)return;const items=data.items.some(i=>i.id===draft.id)?data.items.map(i=>i.id===draft.id?draft:i):[...data.items,draft];if(await save(items, data.items.some(i=>i.id===draft.id) ? 'Content updated successfully.' : 'Content saved successfully.'))setDraft(null)}}><div className="benefits-heading"><h2>{data?.items.some(i=>i.id===draft.id)?'Edit Content':'Add Content'}</h2><button type="button" disabled={busy} onClick={()=>setDraft(null)} aria-label="Close editor"><LuX /></button></div><fieldset disabled={disabled}><div className="benefits-form-grid"><label>Title *<input autoFocus required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<input maxLength={300} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div><label>Icon</label><div className="benefits-icon-field"><button type="button" onClick={()=>setPicker(true)}><IconPreview icon={draft.icon}/>{draft.icon?.name||'Choose an icon'}<small>{draft.icon?.library==='fa6'?'FONT AWESOME 6':draft.icon?'LUCIDE':''}</small></button>{draft.icon&&<button type="button" aria-label="Clear icon" onClick={()=>setDraft({...draft,icon:null})}><LuX /></button>}</div></div><label>Position<input type="number" required min={0} max={100000} step={1} value={draft.position} onChange={e=>setDraft({...draft,position:Number(e.target.value)})}/></label></div><label className="benefits-checkbox"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>{visibilityLabel}</label><div className="benefits-actions"><button type="button" onClick={()=>setDraft(null)}>Cancel</button><button className="benefits-primary" type="submit">{busy?'Saving...':'Save Content'}</button></div></fieldset></form>}
 {loading?<p role="status">Loading benefits...</p>:data?.items.length===0?<p>No benefits yet. Add Content to create one.</p>:<div className="benefits-list">{[...(data?.items??[])].sort((a,b)=>a.position-b.position).map(item=><article key={item.id} className="benefits-row"><div className="benefits-icon"><IconPreview icon={item.icon}/></div><div className="benefits-details"><strong>{item.title}</strong><small>Position {item.position}</small>{item.description&&<p>{item.description}</p>}</div><div className="benefits-actions"><button className={item.active?'benefits-active':''} aria-label={`Toggle ${item.title}`} aria-pressed={item.active} disabled={disabled||!!draft} onClick={()=>void save(data!.items.map(i=>i.id===item.id?{...i,active:!i.active}:i))}><LuPower /></button><button className="benefits-edit" disabled={disabled||!!draft} aria-label={`Edit ${item.title}`} onClick={()=>{setDraft(item)}}><LuPencil /></button><button className="benefits-delete" disabled={disabled||!!draft} aria-label={`Delete ${item.title}`} onClick={()=>{if(window.confirm(`Delete “${item.title}”?`))void save(data!.items.filter(i=>i.id!==item.id))}}><LuTrash2 /></button></div></article>)}</div>}
 {picker&&draft&&<IconPicker value={draft.icon} onClose={()=>setPicker(false)} onSelect={icon=>setDraft({...draft,icon})}/>}
 </section>;
}
