'use client';
/* eslint-disable @next/next/no-img-element -- Order snapshots contain backend-managed media URLs. */

import { useCallback, useEffect, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import type { IconType } from 'react-icons';
import { FaBox, FaCheckCircle, FaChevronLeft, FaChevronRight, FaClock, FaEye, FaSearch, FaSpinner, FaTimes, FaTruck } from 'react-icons/fa';
import { PENDING_ORDER_COUNT_EVENT } from '@/lib/admin-events';

const statuses = ['pending', 'confirmed', 'processing', 'ready_for_delivery', 'out_for_delivery', 'delivered', 'cancelled', 'returned'] as const;
type Status = typeof statuses[number];
type ComboComponent = { productId: string; name: string; type: string; sku: string; image: string; variationId: string; variation: string; quantity: number };
type OrderItem = { productId: string; name: string; type?: string; sku: string; image: string; variation: string; quantity: number; unitPrice: number; lineTotal: number; comboComponents?: ComboComponent[] };
type Order = {
  _id: string; orderNumber: string; customer: { fullName: string; phone: string }; address: { division: string; district: string; street: string }; note: string;
  items: OrderItem[];
  subtotal: number; deliveryCharge: number; discount: number; total: number; payment: { method: string; status: string }; status: Status;
  statusHistory: Array<{ status: Status; note: string; changedBy: string; createdAt: string }>;
  courier: { provider: string; consignmentId: string; trackingCode: string }; createdAt: string;
};
type Result = { data: Order[]; stats: Record<string, number>; pagination: { page: number; pages: number; total: number } };

const labels: Record<Status, string> = { pending: 'Pending', confirmed: 'Confirmed', processing: 'Processing', ready_for_delivery: 'Ready for Delivery', out_for_delivery: 'Out for Delivery', delivered: 'Delivered / Completed', cancelled: 'Cancelled', returned: 'Returned' };
const transitions = Object.fromEntries(statuses.map(status => [status, statuses.filter(candidate => candidate !== status)])) as Record<Status, Status[]>;
const statusClass = Object.fromEntries(statuses.map(status => [status, 'bg-violet-100 text-violet-700'])) as Record<Status, string>;
const money = (value: number) => `\u09F3${Number(value || 0).toLocaleString('en-BD')}`;
const date = (value: string) => new Date(value).toLocaleString('en-BD', { dateStyle: 'medium', timeStyle: 'short' });
const endpoint = '/api/v1/auth/orders';

function OrderProductCard({ item, index }: { item: OrderItem; index: number }) {
  return <article className="rounded-lg border border-slate-200 bg-slate-50 p-3" key={`${item.productId}-${index}`}>
    <div className="grid grid-cols-[56px_minmax(0,1fr)_auto] items-center gap-3">{item.image ? <img className="size-14 rounded-lg bg-white object-cover" src={item.image} alt="" /> : <span className="grid size-14 place-items-center rounded-lg bg-white text-slate-400"><FaBox /></span>}<div className="min-w-0"><strong className="block truncate text-[13px]">{item.name}</strong>{item.variation ? <span className="mt-1 inline-flex max-w-full items-center gap-1 rounded-md bg-violet-100 px-2 py-1 text-[10px] font-bold text-violet-700" title={item.variation}><FaCheckCircle className="shrink-0" aria-hidden="true" /><span className="truncate">{item.variation}</span></span> : <small className="mt-1 block truncate text-[10px] text-slate-500">{item.sku}</small>}<small className="mt-1 block text-[10px] text-slate-500">{money(item.unitPrice)} × {item.quantity}</small></div><b className="text-sm">{money(item.lineTotal)}</b></div>
    {item.type === 'combo' && Boolean(item.comboComponents?.length) && <div className="mt-3 border-t border-slate-200 pt-3"><span className="mb-2 block text-[10px] font-bold tracking-[.06em] text-violet-700 uppercase">Included products</span><div className="grid gap-2">{item.comboComponents!.map((component, componentIndex) => <div className="grid grid-cols-[38px_minmax(0,1fr)_auto] items-center gap-2.5 rounded-md border border-slate-200 bg-white p-2" key={`${component.productId}-${component.variationId}-${componentIndex}`}>{component.image ? <img className="size-[38px] rounded-md object-cover" src={component.image} alt="" /> : <span className="grid size-[38px] place-items-center rounded-md bg-slate-100 text-slate-400"><FaBox /></span>}<div className="min-w-0"><strong className="block truncate text-[11px]">{component.name}</strong><small className="mt-0.5 block truncate text-[9px] text-slate-500">{component.sku || 'No SKU'}</small>{component.variation && <span className="mt-1 inline-flex rounded-full bg-violet-100 px-2 py-0.5 text-[9px] font-semibold text-violet-700">{component.variation}</span>}</div><span className="rounded-md bg-orange-50 px-2 py-1 text-[10px] font-bold text-orange-600">Qty: {component.quantity}</span></div>)}</div></div>}
  </article>;
}

function OrderDetailsModal({ order, busy, close, updateStatus }: { order: Order; busy: boolean; close: () => void; updateStatus: (order: Order, status: Status) => Promise<void> }) {
  const modalRef = useRef<HTMLElement>(null);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const originalOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    modalRef.current?.focus();
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !busy) close();
      if (event.key !== 'Tab') return;
      const items = Array.from(modalRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), select:not(:disabled), a[href]') ?? []);
      if (!items.length) return;
      const first = items[0]; const last = items.at(-1)!;
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
      if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener('keydown', onKeyDown);
    return () => { document.body.style.overflow = originalOverflow; document.removeEventListener('keydown', onKeyDown); previous?.focus(); };
  }, [busy, close]);

  return <div className="fixed inset-0 z-[1000] grid place-items-center bg-slate-950/55 p-5 backdrop-blur-[7px] max-sm:p-3" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && !busy) close(); }}>
    <section ref={modalRef} tabIndex={-1} className="max-h-[92vh] w-[min(980px,calc(100vw-32px))] overflow-hidden rounded-xl border border-slate-200 bg-white text-[#171542] shadow-[0_25px_70px_rgba(15,23,42,.3)] outline-none" role="dialog" aria-modal="true" aria-labelledby="order-detail-title">
      <header className="flex items-start justify-between border-b border-slate-200 px-6 py-5 max-sm:px-4"><div><span className="text-[10px] font-extrabold tracking-[.12em] text-violet-700">ORDER DETAILS</span><h2 id="order-detail-title" className="mt-1 text-xl font-bold">#{order.orderNumber}</h2><small className="mt-1 block text-xs text-slate-500">{date(order.createdAt)}</small></div><button className="grid size-9 place-items-center rounded-lg border-0 bg-violet-50 text-lg text-violet-700 hover:bg-violet-100" type="button" onClick={close} disabled={busy} aria-label="Close order details"><FaTimes /></button></header>
      <div className="max-h-[calc(92vh-94px)] overflow-y-auto p-6 max-sm:p-4">
        <div className="mb-5 flex items-center justify-between gap-4 rounded-xl bg-violet-50 p-4 max-sm:flex-col max-sm:items-start"><div><strong className="block text-sm">Order status</strong><small className="mt-1 block text-xs text-slate-500">Select any status from the complete order workflow.</small></div><select className="min-h-10 min-w-48 rounded-full border-0 bg-violet-100 px-3 text-xs font-bold text-violet-700 outline-none" disabled={busy} value={order.status} onChange={event => void updateStatus(order, event.target.value as Status)}>{statuses.map(item => <option key={item} value={item}>{labels[item]}</option>)}</select></div>
        <div className="grid grid-cols-[minmax(0,1.45fr)_minmax(280px,.75fr)] gap-5 max-lg:grid-cols-1">
          <div className="grid content-start gap-5">
            <section className="rounded-xl border border-slate-200 p-4"><h3 className="mb-3 text-sm font-bold">Products</h3><div className="grid gap-2.5">{order.items.map((item, index) => <OrderProductCard item={item} index={index} key={`${item.productId}-${index}`} />)}</div></section>
            <section className="rounded-xl border border-slate-200 p-4"><h3 className="mb-3 text-sm font-bold">Status history</h3><ol className="grid gap-3">{[...order.statusHistory].reverse().map((entry, index) => <li className="flex gap-3" key={`${entry.createdAt}-${index}`}><FaCheckCircle className="mt-0.5 shrink-0 text-emerald-500" /><div><strong className="block text-xs">{labels[entry.status]}</strong><small className="mt-1 block text-[10px] text-slate-500">{date(entry.createdAt)}</small>{entry.note && <p className="mt-1 text-xs text-slate-600">{entry.note}</p>}</div></li>)}</ol></section>
          </div>
          <div className="grid content-start gap-5">
            <section className="rounded-xl border border-slate-200 p-4"><h3 className="mb-3 text-sm font-bold">Customer & delivery</h3><dl className="grid gap-3 text-xs"><div><dt className="text-slate-500">Name</dt><dd className="mt-1 font-semibold">{order.customer.fullName}</dd></div><div><dt className="text-slate-500">Phone</dt><dd className="mt-1 font-semibold">{order.customer.phone}</dd></div><div><dt className="text-slate-500">Address</dt><dd className="mt-1 font-semibold leading-5">{order.address.street}, {order.address.district}, {order.address.division}</dd></div>{order.note && <div><dt className="text-slate-500">Delivery note</dt><dd className="mt-1 font-semibold leading-5">{order.note}</dd></div>}</dl></section>
            <section className="rounded-xl border border-slate-200 p-4"><h3 className="mb-3 text-sm font-bold">Payment summary</h3><dl className="grid gap-2.5 text-xs"><div className="flex justify-between gap-4"><dt className="text-slate-500">Subtotal</dt><dd className="font-semibold">{money(order.subtotal)}</dd></div>{order.deliveryCharge > 0 && <div className="flex justify-between gap-4"><dt className="text-slate-500">Delivery</dt><dd className="font-semibold">{money(order.deliveryCharge)}</dd></div>}{order.discount > 0 && <div className="flex justify-between gap-4"><dt className="text-slate-500">Discount</dt><dd className="font-semibold">−{money(order.discount)}</dd></div>}<div className="mt-1 flex justify-between gap-4 border-t border-dashed border-slate-200 pt-3 text-sm"><dt className="font-bold">Total</dt><dd className="font-bold">{money(order.total)}</dd></div><div className="mt-1 flex justify-between gap-4"><dt className="text-slate-500">Payment</dt><dd className="font-semibold uppercase">{order.payment.method} · {order.payment.status}</dd></div></dl></section>
            <section className="rounded-xl border border-dashed border-violet-300 bg-violet-50 p-4"><div className="flex items-center gap-3 text-violet-700"><FaTruck className="text-xl" /><div><strong className="block text-xs">{order.courier.provider === 'unassigned' ? 'Courier not assigned' : order.courier.provider}</strong><small className="mt-1 block text-[10px] text-violet-500">Prepared for Pathao and Steadfast integration</small>{order.courier.trackingCode && <small className="mt-1 block text-[10px]">Tracking: {order.courier.trackingCode}</small>}</div></div></section>
          </div>
        </div>
      </div>
    </section>
  </div>;
}

export function OrdersManager() {
  const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState<{ search: string; status: 'all' | Status }>({ search: '', status: 'all' }); const [applied, setApplied] = useState(filters); const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<Order | null>(null); const [busy, setBusy] = useState('');
  const closeModal = useCallback(() => setSelected(null), []);
  const load = useCallback(async (next = applied, nextPage = page) => { setLoading(true); try { const params = new URLSearchParams({ search: next.search, status: next.status, page: String(nextPage), limit: '20' }); const response = await fetch(`${endpoint}?${params}`, { cache: 'no-store' }); const json = await response.json(); if (!response.ok) throw new Error(json.error?.message || 'Could not load orders.'); setResult(json); window.dispatchEvent(new CustomEvent(PENDING_ORDER_COUNT_EVENT, { detail: Math.max(0, Number(json.stats?.pending) || 0) })); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not load orders.'); } finally { setLoading(false); } }, [applied, page]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const applyFilters = () => { setPage(1); setApplied({ ...filters }); if (page === 1 && applied.search === filters.search && applied.status === filters.status) void load(filters, 1); };
  const updateStatus = async (order: Order, nextStatus: Status) => { if (nextStatus === order.status) return; setBusy(order._id); try { const response = await fetch(`${endpoint}/${order._id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: nextStatus }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error?.message || 'Could not update order.'); setSelected(current => current?._id === order._id ? json.data : current); toast.success(`Order moved to ${labels[nextStatus]}.`); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not update order.'); } finally { setBusy(''); } };

  const stats = result?.stats ?? {};
  const statCards: Array<[number, string, IconType, string]> = [
    [stats.total ?? 0, 'Total Orders', FaBox, 'bg-indigo-100 text-indigo-700'],
    [stats.pending ?? 0, 'Pending Orders', FaClock, 'bg-orange-100 text-orange-700'],
    [(stats.confirmed ?? 0) + (stats.processing ?? 0) + (stats.ready_for_delivery ?? 0), 'In Fulfilment', FaBox, 'bg-purple-100 text-purple-700'],
    [stats.out_for_delivery ?? 0, 'Out for Delivery', FaTruck, 'bg-sky-100 text-sky-700'],
  ];
  return <main className="admin-orders-page -mx-2 -mt-1 w-[calc(100%+16px)] max-w-none text-[var(--admin-heading)] max-sm:mx-0 max-sm:mt-0 max-sm:w-full">
    <div className="mb-5 grid grid-cols-4 gap-5 max-lg:grid-cols-2 max-sm:grid-cols-1">{statCards.map(([count, label, Icon, color]) => <article className="flex min-h-32 items-center justify-between rounded-md border border-[var(--admin-border)] bg-[var(--admin-surface)] p-5 shadow-[var(--admin-shadow)]" key={label}><div className="grid gap-[15px]"><span className="text-sm text-[var(--admin-muted)]">{label}</span><strong className="text-[27px]">{count}</strong></div><i className={`grid size-11 place-items-center rounded-md text-lg not-italic ${color}`}><Icon /></i></article>)}</div>
    <section className="rounded-md border border-[var(--admin-border)] bg-[var(--admin-surface)] p-5 shadow-[var(--admin-shadow)]"><h2 className="mb-[18px] text-xl">Order List</h2>
    <form className="mb-[18px] grid grid-cols-[minmax(250px,2fr)_minmax(180px,1fr)_auto] gap-3 rounded-xl bg-white/45 p-4 max-lg:grid-cols-2 max-sm:grid-cols-1" onSubmit={event => { event.preventDefault(); applyFilters(); }}><label className="flex min-h-[52px] items-center gap-2.5 rounded-[10px] border border-slate-300 bg-white px-4 focus-within:border-violet-600 focus-within:ring-3 focus-within:ring-violet-600/10 max-lg:col-span-2 max-sm:col-span-1"><FaSearch className="shrink-0" /><input className="h-auto min-h-0 flex-1 appearance-none border-0 bg-transparent p-0 text-sm outline-none shadow-none ring-0 focus:border-0 focus:outline-none focus:ring-0 focus:shadow-none" value={filters.search} placeholder="Search order, customer or phone..." onChange={event => setFilters({ ...filters, search: event.target.value })} /></label><select className="w-full rounded-[9px] border border-slate-300 bg-white px-[13px] py-[11px] text-sm outline-none focus:border-violet-600 focus:ring-3 focus:ring-violet-600/10" value={filters.status} onChange={event => setFilters({ ...filters, status: event.target.value as 'all' | Status })}><option value="all">All Statuses</option>{statuses.map(item => <option key={item} value={item}>{labels[item]}</option>)}</select><button className="flex items-center justify-center gap-2 rounded-[9px] bg-violet-700 px-[13px] py-[11px] font-semibold whitespace-nowrap text-white disabled:opacity-60" type="submit" disabled={loading}>{loading ? <FaSpinner className="animate-spin" /> : <FaSearch />} Apply Filters</button></form>
    <div className="overflow-x-auto rounded-xl border border-[var(--admin-border)]"><table className="w-full min-w-[940px] table-fixed border-collapse"><thead><tr>{[['Order','20%'],['Customer','21%'],['Items','9%'],['Total','12%'],['Status','17%'],['Courier','12%'],['Actions','9%']].map(([label, width]) => <th key={label} style={{ width }} className="bg-violet-100/70 p-3.5 text-left text-[11px] font-bold tracking-[.04em] text-[#43386d] uppercase">{label}</th>)}</tr></thead><tbody>{(result?.data || []).map(order => <tr key={order._id}><td className="border-t border-slate-200 p-3.5 align-middle text-[13px]"><strong className="block truncate" title={order.orderNumber}>{order.orderNumber}</strong><small className="mt-1 block truncate text-[10px] text-[var(--admin-muted)]">{date(order.createdAt)}</small></td><td className="border-t border-slate-200 p-3.5 align-middle text-[13px]"><strong className="block truncate" title={order.customer.fullName}>{order.customer.fullName}</strong><small className="mt-1 block truncate text-[10px] text-[var(--admin-muted)]">{order.customer.phone}</small></td><td className="border-t border-slate-200 p-3.5 align-middle text-[13px]"><strong>{order.items.reduce((sum, item) => sum + item.quantity, 0)}</strong><small className="ml-1 text-[10px] text-[var(--admin-muted)]">items</small></td><td className="border-t border-slate-200 p-3.5 align-middle"><strong className="block text-sm">{money(order.total)}</strong><small className="mt-1 block truncate text-[10px] text-[var(--admin-muted)]">{order.payment.method.toUpperCase()} · {order.payment.status}</small></td><td className="border-t border-slate-200 p-3.5 align-middle"><select className={`min-h-8 w-full rounded-full border-0 px-2.5 text-[10px] font-bold outline-none ${statusClass[order.status]}`} disabled={busy === order._id || transitions[order.status].length === 0} value={order.status} onChange={event => void updateStatus(order, event.target.value as Status)}><option value={order.status}>{labels[order.status]}</option>{transitions[order.status].map(item => <option key={item} value={item}>{labels[item]}</option>)}</select></td><td className="border-t border-slate-200 p-3.5 align-middle"><span className="block truncate text-[11px] text-[var(--admin-muted)]" title={order.courier.provider}>{order.courier.provider === 'unassigned' ? 'Not assigned' : order.courier.provider}</span></td><td className="border-t border-slate-200 p-3.5 align-middle"><button className="grid size-8 place-items-center rounded-lg border-0 bg-violet-50 text-violet-700 hover:bg-violet-100" type="button" title="View order" aria-label={`View order ${order.orderNumber}`} onClick={() => setSelected(order)}><FaEye /></button></td></tr>)}</tbody></table>
      {!loading && !result?.data?.length && <div className="p-14 text-center text-[var(--admin-muted)]"><FaBox className="mx-auto text-4xl" /><h3 className="mt-3 text-[var(--admin-heading)]">No orders found</h3><p>Adjust the filters or wait for a new customer order.</p></div>}{loading && !result?.data?.length && <div className="grid min-h-48 place-items-center text-violet-700"><FaSpinner className="animate-spin text-2xl" /></div>}</div>
    {result && result.pagination.pages > 1 && <footer className="mt-5 flex items-center justify-between border-t border-slate-200 pt-5 text-xs text-[var(--admin-muted)]"><span>Page {page} of {result.pagination.pages} · {result.pagination.total} orders</span><div className="flex gap-2"><button className="grid size-9 place-items-center rounded-lg border-0 bg-violet-50 text-violet-700 disabled:opacity-40" type="button" disabled={page === 1 || loading} onClick={() => setPage(value => value - 1)} aria-label="Previous page"><FaChevronLeft /></button><button className="grid size-9 place-items-center rounded-lg border-0 bg-violet-50 text-violet-700 disabled:opacity-40" type="button" disabled={page === result.pagination.pages || loading} onClick={() => setPage(value => value + 1)} aria-label="Next page"><FaChevronRight /></button></div></footer>}
  </section>{selected && <OrderDetailsModal order={selected} busy={busy === selected._id} close={closeModal} updateStatus={updateStatus} />}</main>;
}
