'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import toast from 'react-hot-toast';
import 'react-quill-new/dist/quill.snow.css';
import './policy-editor.css';
import { preparePolicyHtml } from './prepare-policy-html';
const Editor=dynamic(()=>import('react-quill-new'),{ssr:false});
const endpoint='/api/v1/auth/delivery-policy';
export function PolicyEditor(){
 const [html,setHtml]=useState('');const [version,setVersion]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [conflict,setConflict]=useState(false);const saving=useRef(false);
 useEffect(()=>{const controller=new AbortController();fetch(endpoint,{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Could not load content.');setHtml(j.data.html);setVersion(j.data.version);setConflict(false);setError('')}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[]);
 async function save(){if(version===null||saving.current||conflict)return;saving.current=true;setBusy(true);try{const preparedHtml=await preparePolicyHtml(html);setHtml(preparedHtml);const r=await fetch(endpoint,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({html:preparedHtml,version}),signal:AbortSignal.timeout(15000)});const j=await r.json();if(r.status===409)setConflict(true);if(!r.ok)throw new Error(j.error?.message||'Could not save content.');setHtml(j.data.html);setVersion(j.data.version);setError('');toast.success('Delivery & Returns tab updated.')}catch(e){const message=e instanceof Error?e.message:'Could not save content.';setError(message);toast.error(message)}finally{saving.current=false;setBusy(false)}}
 return <section className="benefits-management policy-editor"><div className="benefits-editor"><div className="benefits-heading"><div><h2>Delivery & Returns tab content</h2></div></div>{error&&<p role="alert" className="benefits-error">{error}</p>}{version===null?<p>Loading content...</p>:<><Editor placeholder="Write delivery and returns content..." theme="snow" value={html} onChange={setHtml} readOnly={busy||conflict} modules={{toolbar:{handlers:{image:function(this:{quill:{getSelection:()=>{index:number}|null;getLength:()=>number;insertEmbed:(index:number,type:string,value:string)=>void}}){const url=window.prompt('Image URL (https://...)');if(!url)return;try{const parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol))throw new Error();this.quill.insertEmbed(this.quill.getSelection()?.index??this.quill.getLength()-1,'image',parsed.href)}catch{toast.error('Enter a valid HTTP or HTTPS image URL.')}}},container:[[{header:[1,2,3,4,5,false]}],['bold','italic','underline'],[{list:'ordered'},{list:'bullet'}],[{align:''},{align:'center'},{align:'right'},{align:'justify'}],['link','image','code-block'],['clean']]}}}/><div className="benefits-actions policy-editor-actions"><button type="button" className="benefits-primary" disabled={busy||conflict} onClick={()=>void save()}>{busy?'Saving...':'Save tab content'}</button></div></>}</div></section>;
}
