'use client';
/* eslint-disable @next/next/no-img-element -- Admin thumbnails use authenticated/proxied media URLs. */
import {useCallback,useEffect,useState} from 'react';
import toast from 'react-hot-toast';
import {LuChevronLeft,LuChevronRight,LuMessageSquareReply,LuSearch,LuStar,LuX} from 'react-icons/lu';
import {FaCheck,FaReply,FaTrashCan,FaXmark} from 'react-icons/fa6';
import {PENDING_REVIEW_COUNT_EVENT} from '@/lib/admin-events';
type Status='pending'|'approved'|'rejected';
type Review={_id:string;productName:string;productSlug:string;productImage?:string;customerName:string;location?:string;rating:number;comment:string;images:string[];status:Status;adminReply?:string;createdAt:string};
type Result={data:Review[];stats:Record<'total'|Status,number>;pagination:{page:number;pages:number;total:number}};
const endpoint='/api/v1/auth/reviews';
export function ReviewsManager({storefrontUrl}:{storefrontUrl:string}){
 const [result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState<'all'|Status>('all'),[page,setPage]=useState(1),[replying,setReplying]=useState<Review|null>(null),[reply,setReply]=useState(''),[busy,setBusy]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setPage(1)},350);return()=>clearTimeout(timer)},[search]);
 const load=useCallback(async()=>{try{const params=new URLSearchParams({page:String(page),limit:'10',status,search:query});const response=await fetch(endpoint+'?'+params,{cache:'no-store'});const json=await response.json();if(!response.ok)throw new Error(json.error?.message||'Failed to load reviews.');setResult(json);window.dispatchEvent(new CustomEvent(PENDING_REVIEW_COUNT_EVENT,{detail:json.stats?.pending??0}))}catch(error){toast.error(error instanceof Error?error.message:'Failed to load reviews.')}finally{setLoading(false)}},[page,status,query]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const mutate=async(id:string,path:string,method:string,body?:unknown,message?:string)=>{setBusy(id+path);try{const response=await fetch(endpoint+'/'+id+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});if(response.status!==204){const json=await response.json();if(!response.ok)throw new Error(json.error?.message||'Update failed.')}if(message)toast.success(message);await load();return true}catch(error){toast.error(error instanceof Error?error.message:'Update failed.');return false}finally{setBusy('')}};
 const stats=result?.stats??{total:0,pending:0,approved:0,rejected:0};
 return <main className="reviews-admin"><header><h1>Product Reviews</h1><p>Manage customer reviews and moderation</p></header><div className="review-stats">{([['Total Reviews',stats.total,'total'],['Pending',stats.pending,'pending'],['Approved',stats.approved,'approved'],['Rejected',stats.rejected,'rejected']] as const).map(([label,value,tone])=><article key={label}><div><span>{label}</span><strong>{value}</strong></div><i className={tone}><LuStar/></i></article>)}</div>
 <section className="review-tools"><label><LuSearch/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search reviews..."/></label><select value={status} onChange={e=>{setStatus(e.target.value as 'all'|Status);setPage(1)}}><option value="all">All Status</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></section>
 <section className="review-table-card">{loading?<p className="review-empty">Loading reviews...</p>:!result?.data.length?<p className="review-empty"><LuStar/>No reviews found</p>:<div className="review-table-scroll"><table><thead><tr><th>Product / Customer</th><th>Rating & Review</th><th>Status</th><th>Actions</th></tr></thead><tbody>{result.data.map(item=>{const productHref=`${storefrontUrl.replace(/\/$/,'')}/products/${encodeURIComponent(item.productSlug)}`;return <tr key={item._id}><td><div className="review-product">{item.productImage?<a href={productHref} target="_blank" rel="noopener noreferrer" aria-label={`Open ${item.productName}`}><img src={item.productImage} alt=""/></a>:<span/>}<div><strong><a href={productHref} target="_blank" rel="noopener noreferrer">{item.productName}</a></strong><small>By: {item.customerName}{item.location?' · '+item.location:''}</small></div></div></td><td><div className="admin-stars">{'★★★★★'.split('').map((star,index)=><span key={index} className={index<item.rating?'active':''}>{star}</span>)}</div><p>{item.comment}</p><small>{new Date(item.createdAt).toLocaleString()}</small>{item.images?.length>0&&<div className="review-images">{item.images.map(image=><img key={image} src={image} alt="Review attachment"/>)}</div>}{item.adminReply&&<div className="review-reply">Reply: {item.adminReply}</div>}</td><td><span className={'review-status '+item.status}>{item.status}</span></td><td><div className="review-actions"><button title="Reply" onClick={()=>{setReplying(item);setReply(item.adminReply??'')}}><FaReply/><span>Reply</span></button>{item.status!=='approved'&&<button className="approve" title="Approve" disabled={!!busy} onClick={()=>void mutate(item._id,'/status','PATCH',{status:'approved'},'Review approved.')}><FaCheck/><span>Approve</span></button>}{item.status!=='rejected'&&<button className="reject" title="Reject" disabled={!!busy} onClick={()=>void mutate(item._id,'/status','PATCH',{status:'rejected'},'Review rejected.')}><FaXmark/><span>Reject</span></button>}<button className="delete" title="Delete" aria-label="Delete" disabled={!!busy} onClick={()=>{if(confirm('Delete this review permanently?'))void mutate(item._id,'','DELETE',undefined,'Review deleted.')}}><FaTrashCan/></button></div></td></tr>})}</tbody></table></div>}
 {result&&result.pagination.pages>1&&<footer><span>Page {page} of {result.pagination.pages} ({result.pagination.total} items)</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}><LuChevronLeft/></button><button disabled={page===result.pagination.pages} onClick={()=>setPage(page+1)}><LuChevronRight/></button></div></footer>}</section>
 {replying&&<div className="admin-review-modal" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setReplying(null)}}><section role="dialog" aria-modal="true" aria-labelledby="reply-title"><header><h2 id="reply-title">Reply to Review</h2><button aria-label="Close" onClick={()=>setReplying(null)}><LuX/></button></header><blockquote>{replying.comment}</blockquote><label>Your Reply (Public)<textarea autoFocus maxLength={2000} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Type your official reply here..."/></label><footer><button onClick={()=>setReplying(null)}>Cancel</button><button className="primary" disabled={busy==='reply'} onClick={async()=>{setBusy('reply');const ok=await mutate(replying._id,'/reply','PATCH',{reply},'Reply saved.');if(ok)setReplying(null)}}><LuMessageSquareReply/>Save Reply</button></footer></section></div>}</main>;
}
